### ISSUE TITLE
PeerAddress not globally reachable. 

### ISSUE THREAD

**Issue by wwwolegwww** [nimiq-network/mining-pool#21]
node index.js --config=server.sample.conf
I have edited that config and can`t use that comand.  Every times i get  "PeerAddress not globally reachable. "
How to handle with that?

**Comment by riptl** [comment]
@wwwolegwww This error looks like invalid configuration, so I'm going to close this. This issue tracker is meant for bug reports and feature suggestions, not for support. The Nimiq support Telegram group might be able to help you further: https://t.me/NimiqSupport
