### ISSUE TITLE
Error: MDB_CORRUPTED: Located page was wrong type

### ISSUE THREAD

**Issue by Snajper88** [nimiq-network/mining-pool#8]
https://github.com/skypool-org/skypool-nimiq-miner/issues/17
![image](https://user-images.githubusercontent.com/20987020/39496747-231850c4-4da0-11e8-8ce5-bccaa0a7e72a.png)

Not even changing a thing in the config.txt.

**Comment by fiaxh** [comment]
The error is not related to the mining pool. As the error message indicates, your database is corrupt. Removing your `peer-key/` folder should quick-fix it.

**Comment by sisou** [comment]
Sadly, I have the same problem, and also after deleting the `peer-key` directory. It gets recreated at start-up and then failed to read. Seems like LMDB has problems under WSL.

**Comment by Snajper88** [comment]
Sooooo, no WSL anymore?

**Comment by AlessandroVol23** [comment]
I have exactly the same error on Windows 10 and WSL. 
I tried the example from this repository: https://github.com/kermitt2/delft
```shell
python toxicCommentClassifier.py train
```
And get this error:

```python
Traceback (most recent call last):
  File "toxicCommentClassifier.py", line 103, in <module>
    train(embeddings_name=embeddings_name, fold_count=args.fold_count, architecture=architecture, use_ELMo=use_ELMo, use_BERT=use_BERT)
  File "toxicCommentClassifier.py", line 27, in train
    embeddings_name=embeddings_name, use_ELMo=use_ELMo, use_BERT=use_BERT, batch_size=batch_size, maxlen=maxlen)
  File "/d/repo/delft/delft/textClassification/wrapper.py", line 65, in __init__
    self.embeddings = Embeddings(embeddings_name, use_ELMo=use_ELMo, use_BERT=use_BERT)
  File "/d/repo/delft/delft/utilities/Embeddings.py", line 65, in __init__
    self.make_embeddings_simple(name)
  File "/d/repo/delft/delft/utilities/Embeddings.py", line 296, in make_embeddings_simple
    self.make_embeddings_lmdb(name, hasHeader)
  File "/d/repo/delft/delft/utilities/Embeddings.py", line 218, in make_embeddings_lmdb
    txn.put(word.encode(encoding='UTF-8'), _serialize_pickle(vector))
lmdb.CorruptedError: mdb_put: MDB_CORRUPTED: Located page was wrong type
```

I deleted the database file which didn't help as well.
